name: Git generate and push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install pylint
        pip install -r requirements.txt

    - name: setup git credentials
      run: |
        git config --global user.name "m4tice"
        git config --global user.email "ductuan2908@gmail.com"

    - name: clear directory
      run: |
        git rm _out/*
        git commit -m "remove generated files"

    - name: Run generator
      run: |
        # Run the generator script
        mkdir -p _out
        python main.py

    - name: push changes to remote
      run: |
        git add _out; git commit -m "update: generated files"
        git push
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint $(git ls-files '*.py')
    # - name: Testing the code with pytest
    #   run: |
    #     python -m pytest
